//
//  ContentView.swift
//  TestPublishJazzyDocs
//
//  Created by Adam Hoyle on 17/03/2020.
//  Copyright © 2020 Adam Hoyle Associates. All rights reserved.
//

import SwiftUI

/**
 Content for the app
 - SeeAlso: any vanilla app generated by Xcode
 */
public struct ContentView: View {
    /**
        The body of the view
     - Returns: `some View`, (standard for SwiftUI)
     */
    public var body: some View {
        Text("Hello, World!")
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
